name: Buffrs Registry

on:
  push:
    branches: ["main"]
  pull_request:

env:
  MINIMUM_LINE_COVERAGE_PERCENT: 5

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add rustfmt
      - run: cd registry && cargo fmt --check --all

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v2
      - run: rustup update && rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cd registry && cargo clippy --all-targets --workspace -- -D warnings -D clippy::all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - uses: arduino/setup-protoc@v2
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./registry/docker-compose.yml"
      - run: rustup update
      # run registry locally to permit API tests
      - name: "Run Registry in background"
        working-directory: registry
        run: |
          cargo build --release
          ./target/release/buffrs-registry --filesystem-storage /tmp &
        env:
          LISTEN: 127.0.0.1:4367
      - uses: Swatinem/rust-cache@v2
      - run: cd registry && cargo test --workspace
        env:
          RUST_BACKTRACE: 1

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-deny || true
      - run: cd registry && cargo deny --workspace check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: arduino/setup-protoc@v2
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./registry/docker-compose.yml"
      - run: rustup update
      - run: rustup component add llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-llvm-cov || true
      # run registry locally to permit API tests
      - name: "Run Registry in background"
        working-directory: registry
        run: |
          cargo build --release
          ./target/release/buffrs-registry --filesystem-storage /tmp &
        env:
          LISTEN: 127.0.0.1:4367
      - run: cd registry && cargo llvm-cov --workspace --fail-under-lines "$MINIMUM_LINE_COVERAGE_PERCENT"

# TODO: This already runs across registiry folder in cli.yml, maybe it's time to extract common.yml?
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo install typos-cli@=1.16.26 --locked || true
      - run: cd registry && typos
