name: Buffrs Registry

on:
  push:
    branches: ["main"]
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'deny.toml'
      - 'src/**'
      - 'registry/**'
  pull_request:
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'deny.toml'
      - 'src/**'
      - 'registry/**'

env:
  MINIMUM_LINE_COVERAGE_PERCENT: 5

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add rustfmt
      - run: cd registry && cargo fmt --check --all

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v2
      - run: rustup update && rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cd registry && cargo clippy --all-targets --workspace -- -D warnings -D clippy::all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - uses: arduino/setup-protoc@v2
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./registry/docker-compose.yml"
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cd registry && cargo test --workspace
        env:
          RUST_BACKTRACE: 1

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-deny || true
      - run: cd registry && cargo deny --workspace check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: arduino/setup-protoc@v2
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./registry/docker-compose.yml"
      - run: rustup update
      - run: rustup component add llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-llvm-cov || true
      - run: cd registry && cargo llvm-cov --workspace --fail-under-lines "$MINIMUM_LINE_COVERAGE_PERCENT"

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo install typos-cli || true
      - run: cd registry && typos
